# Generated by Django 4.2.4 on 2023-08-07 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carbrand',
            options={'verbose_name': 'марку машины', 'verbose_name_plural': 'Марки машин'},
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение машины')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_bot.carbrand', verbose_name='Марка машины')),
            ],
            options={
                'verbose_name': 'машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
