# Generated by Django 4.2.4 on 2023-08-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bot', '0002_alter_carbrand_options_alter_carbrand_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'машину', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
